Document: reboot-check
Title: Debian reboot-check Manual
Author: <insert document author here>
Abstract: This manual describes what reboot-check is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/reboot-check/reboot-check.sgml.gz

Format: postscript
Files: /usr/share/doc/reboot-check/reboot-check.ps.gz

Format: text
Files: /usr/share/doc/reboot-check/reboot-check.text.gz

Format: HTML
Index: /usr/share/doc/reboot-check/html/index.html
Files: /usr/share/doc/reboot-check/html/*.html
